### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ghost** [TouchTone/make_contact#1]
Running the last known version released as of this post. Quality is set to 70, Width is set to 700, No cover, no technical details, and the folder I added has 847 images in it. It crashes around 94% every time (Windows 7).

**Comment by TouchTone** [comment]
Sorry for the late response, haven't check this in a while. Can you try to run the program from a command line? If it crashes it should print a stack trace to help identify where it crashed. 

847 is quite a lot of images, it is possible that it's running out of memory (it keeps the thumbnails in memory to speed up the process). Can you check to see if that's the case?

Thanks!

**Comment by ghost** [comment]
I don't have the folder of images anymore. But I can tell you that I have collaged ~600 images before with no problem.

**Comment by TouchTone** [comment]
Ran a test on a directory with ~4000 images (~4G). Running it through make_contact worked fine, but it used up to 6G of memory in the process (and created a 1000x43733 pixel contact sheet for 100 pixel thumbnails ;).

So I can't reproduce the crash, but make sure you have a LOT of memory if you're trying to do large directories.
